[deployment-docker] Fixes init.sql not being executed when root_password is set
Summary:
We recently introduced ROOT_PASSWORD as a mandatory environment variable for the cluster-in-a-box
Docker image. What we didn't realize is that adding this actually broke the automatic execution of
the `/init.sql` file.

Prior to introducing ROOT_PASSWORD, if there existed a file called `/init.sql` (in the root `/`
directory), it would get auto-executed when the container is initialized. This behavior is described
here:

https://github.com/memsql/deployment-docker#automatically-run-sql-when-cluster-in-a-box-initializes

More information here: https://github.com/memsql/deployment-docker/issues/2

Test Plan:
```
make test-ciab
```

and

https://app.circleci.com/pipelines/github/memsql/deployment-docker/88/workflows/9365b5eb-1f15-41e0-8d83-437d97289015

Reviewers: carl, vtkachuk-ua

Reviewed By: carl

Subscribers: fmagalhaes, engineering-list

Differential Revision: https://grizzly.internal.memcompute.com/D44701

diff --git a/test/ciab b/test/ciab
--- a/test/ciab
+++ b/test/ciab
@@ -62,11 +62,13 @@ wait-start() {
 }
 
 docker rm -f memsql-ciab || ( echo "no container to cleanup before test" )
+echo "CREATE DATABASE IF NOT EXISTS db1;" > init.sql
 docker run -i --init \
     --name memsql-ciab \
     -e LICENSE_KEY=${LICENSE_KEY} \
     -e ROOT_PASSWORD=${ROOT_PASSWORD} \
     -v memsql-ciab:/var/lib/memsql \
+    -v ${PWD}/init.sql:/init.sql \
     ${IMAGE}
 
 docker start memsql-ciab
@@ -81,6 +83,15 @@ echo "verifying studio is running"
 
 MASTER_ID=$(memsqlctl list-nodes --role master -q)
 [[ -n ${MASTER_ID} ]] || ( echo "no master found"; exit 1 )
+
+echo "verifying that init.sql ran and created a database called db1"
+DB_LIST=$(run memsql -e "select schema_name from information_schema.schemata;" --batch --password=${ROOT_PASSWORD})
+
+# We expect `db1` to be a substring of `DB_LIST`
+if [[ "${DB_LIST}" != *"db1"* ]]; then
+    echo "Database 'db1' was not found in the cluster which means that init.sql did not run as expected"
+    exit 1
+fi
 
 echo "verifying queries & creating test data"
 memsqlctl query --memsql-id ${MASTER_ID} -e "create database test" -p ${ROOT_PASSWORD}
@@ -115,6 +126,7 @@ docker run -d --init \
     -e LICENSE_KEY=${LICENSE_KEY} \
     -e ROOT_PASSWORD=${ROOT_PASSWORD} \
     -v memsql-ciab:/var/lib/memsql \
+    -v ${PWD}/init.sql:/init.sql \
     ${IMAGE}
 
 wait-start
@@ -129,3 +141,4 @@ if [[ "${COUNT}" != "${COUNT_AFTER_RECREATE}" ]]; then
 fi
 
 echo "success"
+rm init.sql
