adds test

diff --git a/test/ciab b/test/ciab
--- a/test/ciab
+++ b/test/ciab
@@ -67,6 +67,7 @@ docker run -i --init \
     -e LICENSE_KEY=${LICENSE_KEY} \
     -e ROOT_PASSWORD=${ROOT_PASSWORD} \
     -v memsql-ciab:/var/lib/memsql \
+    -v ./init.sql:/init.sql \
     ${IMAGE}
 
 docker start memsql-ciab
@@ -81,6 +82,14 @@ echo "verifying studio is running"
 
 MASTER_ID=$(memsqlctl list-nodes --role master -q)
 [[ -n ${MASTER_ID} ]] || ( echo "no master found"; exit 1 )
+
+echo "verifying that init.sql ran and created a database called db1"
+DB1_COUNT=$(run memsql -e "select count(*) from information_schema.schemata where schema_name="db1";" --batch --password=${ROOT_PASSWORD})
+
+if [[ "${DB1_COUNT}" != "1" ]]; then
+    echo "Database 'db1' was not found in the cluster which means that init.sql did not run as expected"
+    exit 1
+fi
 
 echo "verifying queries & creating test data"
 memsqlctl query --memsql-id ${MASTER_ID} -e "create database test" -p ${ROOT_PASSWORD}
